all: 
	python3 spamclfstpwrds.py part1 > res1
	python3 spamclfstpwrds.py part2 > res2
	python3 spamclfstpwrds.py part3 > res3
	python3 spamclfstpwrds.py part4 > res4
	python3 spamclfstpwrds.py part5 > res5
	python3 spamclfstpwrds.py part6 > res6
	python3 spamclfstpwrds.py part7 > res7
	python3 spamclfstpwrds.py part8 > res8
	python3 spamclfstpwrds.py part9 > res9
	python3 spamclfstpwrds.py part10 > res10

clean: 
	rm res*