all: 
	python3 genvect.py part1
	python3 genvect.py part2
	python3 genvect.py part3
	python3 genvect.py part4
	python3 genvect.py part5
	python3 genvect.py part6
	python3 genvect.py part7
	python3 genvect.py part8
	python3 genvect.py part9
	python3 genvect.py part10

clean: 
	rm *vec *labels